### ISSUE TITLE
How to implement it on laravel

### ISSUE THREAD

**Issue by omarherri** [shino47/ckeditor5-build-laravel-image#1]
Hi, your package fit perfectly my needs, but i'm struggling to implement it.

I did install it with npm but how to require it with laravel mix, because chrome says ClassicEditor is not defined.

**Comment by shino47** [comment]
Hi. Just add this build as a script in your `webpack.mix.js` file:

```javascript
mix.scripts([
  'node_modules/ckeditor5-build-laravel-image/build/ckeditor.js',
], 'public/js/vendors.js');
```

Remember to refer this generated file in your documents:

```html
<script src="js/vendors.js></script>
```

Also, I added this info in the readme

**Comment by omarherri** [comment]
Thank you so much for you help. i updated my webpack and work like a charm
